#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: netflix-clone
#  namespace: default
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
  
#spec:
#  rules:
#    - host: a7c4ad77dd3514a6aaee25a2f4da8a9d-325979674.us-east-2.elb.amazonaws.com
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: netflix-clone
#                port:
#                  number: 80
#  ingressClassName: nginx