apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-netflix-clone-chart
  labels:
    app: netflix-clone-netflix-clone-chart
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: netflix-clone-netflix-clone-chart
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "netflix-clone.example.com"